spring:
  #\u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #\u6570\u636E\u5E93\u94FE\u63A5\u9A71\u52A8
    name: springboot_study  #\u6570\u636E\u5E93\u540D
    url: jdbc:mysql://localhost:3306/springboot_study?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root #\u7528\u6237\u540D
    password: root123 #\u5BC6\u7801

#mybatis\u7684\u76F8\u5173\u914D\u7F6E
mybatis:
  #mapper\u914D\u7F6E\u6587\u4EF6
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.homework.model
  #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D
  configuration:
    map-underscore-to-camel-case: true
